"""add unique constraint to booking

Revision ID: 171fa60312b1
Revises: 1917e729bf52
Create Date: 2026-09-04 10:29:55.047413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '171fa60312b1'
down_revision: Union[str, Sequence[str], None] = '1917e729bf52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'booking', ['user_id', 'event_id'])
    op.add_column('user', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.drop_constraint(None, 'booking', type_='unique')
    # ### end Alembic commands ###
