"""add booking open at

Revision ID: 9dc5281ce3ad
Revises: 16813fc1851a
Create Date: 2026-09-04 20:54:32.723163

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9dc5281ce3ad'
down_revision: Union[str, Sequence[str], None] = '16813fc1851a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('booking_open_at', sa.DateTime(), nullable=False))
    op.drop_column('event', 'booking_opens_at')
    op.create_foreign_key(None, 'waitlist', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'waitlist', 'event', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'waitlist', type_='foreignkey')
    op.drop_constraint(None, 'waitlist', type_='foreignkey')
    op.add_column('event', sa.Column('booking_opens_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('event', 'booking_open_at')
    # ### end Alembic commands ###
