"""Add created_at to events

Revision ID: d4f50ff99333
Revises: 9dc5281ce3ad
Create Date: 2026-09-06 19:53:22.915935

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4f50ff99333'
down_revision: Union[str, Sequence[str], None] = '9dc5281ce3ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "event",
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=True
        )
    )

    op.execute(
        "UPDATE event SET created_at = NOW() WHERE created_at IS NULL"
    )

    op.alter_column(
        "event",
        "created_at",
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'created_at')
    # ### end Alembic commands ###
