"""Create booking_open_at column

Revision ID: d7e6e1f8fc23
Revises: 3e9838d45d84
Create Date: 2026-09-04 11:52:12.820481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd7e6e1f8fc23'
down_revision: Union[str, Sequence[str], None] = '3e9838d45d84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('booking_opens_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'booking_opens_at')
    # ### end Alembic commands ###
